### ISSUE TITLE
Constant Buffering and Play Store

### ISSUE THREAD

**Issue by oilrig11** [AbdullahSako/ChikiChikiTube-Android#5]
I've been running into constant buffering that isn't present in the website itself. I've tested it with a Motorola G Power and Fire HD8 and they both have this issue. 

I also recently found chikichiki uploaded on to the play store but I've only seen references of the app being on fdroid, just wanted to check if the one who published the app is you.

Thank you.

**Comment by AbdullahSako** [comment]
Hey
It will take me a some time to check it out since i am very busy for the few upcoming days.
Also about the play store it wasnt me who uploaded it there, so i sent the uploader an email to remove it
Thanks for bringing this up

**Comment by AbdullahSako** [comment]
Hello @oilrig11 
i know i am late but could you tell me the android version of both devices ?

**Comment by oilrig11** [comment]
Android 9 for HD8 and 11 for Moto. 

I've run into an issue where the bar that appears when using gesture navigation that shows you where to swipe to reach home doesn't disappear in full screen if you accidentally trigger it. This results in the gesture bar blocking an entire row of subtitles at the bottom of the screen. This isn't shared with the online site.

It would be great if you could implement a pop up video  function as well. I've tried split screen but it isn't quite the same.

**Comment by AbdullahSako** [comment]
So it seems it the constant buffering for HD8 and Motorola G Power might be a bug in the library i am using to run videos (exoplayer) , it might work as i have updated it.
normal navigation and status bar would appear on my xiaomi device in full screen (on my old samsung device it was working fine) and i fixed it so i believe the gesture navigation bar showing up should be fixed too.
if it does not get fixed could you open another issue if that does not bother you.

as for pop up video function, ive added picture in picture mode in full screen for supported devices (android Oreo and above) you will be able to open it using a button in the corner in full screen video, but personally on my xiaomi device and my old samsung device there is floating window options which is much better than picture in picture as you can resize the window however much you want, maybe your device has that too?.

in few days v1.7 will be on fdroid where these fixes are applied

Thanks you for reporting these bugs.
